### PR TITLE
Ignore content files of LeapMotionCoreAssets package

### PR DESCRIPTION
**Pull request by tomoasleep**
Ignore `Assets/Gizmos` and `Assets/Plugins` because [Leap package](https://github.com/leapmotion-examples/LeapMotionCoreAssets/tree/develop/Assets) contains these files.

### CODE REVIEW

**Comment by tomoasleep** [comment]
Review please

**Comment by tomoasleep** [comment]
Stopped ignoring `Assets/ProjectSettings` (because these files are needed).

**Comment by takuti** [comment]
cloneからleap core assetsのimport, buildまでを再現したので :innocent: です〜！！！！！

**Comment by tomoasleep** [comment]
:innocent:

**Pull request merged**
