### PR TITLE
Don't ignore meta files

### PR DESCRIPTION
**Pull request by tomoasleep**
Sorry, I didn't know that meta files of asset files are used by scenes to refer the asset files.
I remove `*.meta` from `.gitignore` not to ignore meta files.

References (Not official):
http://qiita.com/wordijp/items/3e4b87756fd11c893a9d
http://answers.unity3d.com/questions/932348/visible-or-hidden-meta-files-with-git.html

Review plz @Sushisushi-sandesu/all

### CODE REVIEW

**Comment by natezzz** [comment]
@tomoasleep OMG. Now everyone has his own copy of .meta files. Whose .meta files should we start tracking again?

According to [this](http://unity3diy.blogspot.jp/2014/06/using-git-with-3d-games-source-control_8.html), we need to change the version control mode to "Visible meta files" too.

**Comment by tomoasleep** [comment]
I'm planning that I or you add .meta files in this pull request now and other ones delete their own .meta files.

**Comment by natezzz** [comment]
@tomoasleep Please add the .meta files. We will sync with yours.

**Comment by tomoasleep** [comment]
:ok_woman:

**Comment by tomoasleep** [comment]
@natezzz After we merge this PR, please let the PR https://github.com/Sushisushi-sandesu/sushi/pull/11 merge (or rebase) the updated master branch.

**Comment by natezzz** [comment]
@tomoasleep Is the PR #11 approved for a merge?

**Comment by tomoasleep** [comment]
@natezzz No. In order to check if the PR #11 moves, we have to merge changes **from** the updated master branch **into** the branch camera_app (#11). (we run `git merge master` on camera_app.)
(Otherwise, we have to rebase camera_app branch on the updated master branch.)

**Comment by tomoasleep** [comment]
Retracked existing .meta files.

**Comment by natezzz** [comment]
@tomoasleep Review passed.

**Comment by natezzz** [comment]
@tomoasleep So the next steps are:
1. You merge this PR into master.
2. I merge master into camera-app.
3. Review camera-app.
4. Merge camera-app back into master.

Is that correct?

**Comment by tomoasleep** [comment]
@natezzz Yes, that's right.

**Comment by natezzz** [comment]
@tomoasleep :ok_woman:

**Comment by tomoasleep** [comment]
@Sushisushi-sandesu/all another one please review this PR.

**Comment by harihitode** [comment]
I've caught up. Thanks your research.
- All *.meta files for scripts (or other files) should be included in our commit.
- This request has removed "*.meta files" from gitignore.

Am I right?

**Comment by tomoasleep** [comment]
@harihitode Yes, that's right :ok_hand:

**Comment by neetp7k9** [comment]
Thanks for your effort, I will include *.meta in my commit.

**Comment by tomoasleep** [comment]
It's OK to merge?

**Comment by harihitode** [comment]
yes. no problem.

**Comment by tomoasleep** [comment]
thx~

**Pull request merged**
