### PR TITLE
 CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by harihitode**
Anyway I'll try. please give me comments :)

### CODE REVIEW

**Comment by ganmacs** [comment]
Ref #19

**Comment by takuti** [comment]
I guess it's enough if CONTRIBUTING.md has the following content:

```
You can freely create issues to:

- write ideas and share useful links
- show future tasks

1. Checkout a branch for new feature
2. Create a pull request ASAP with "[WIP]"
3. Implement, commit and push to the branch
4. Ready to review -> remove "[WIP]" and call at least 2 reviewers
5. Fix your implementation based on review comments
6. Get 2 LGTMs -> Merge the branch and remove it
```

This task is important, but writing code is more important task. So, we need to finish this as soon as possible :runner: 

@harihitode plz finish this and move to reviewing process :bow:

**Comment by takuti** [comment]
Hi @Sushisushi-sandesu/all,

I have quickly finished @harihitode's CONTRIBUTING.md task. Please review and comments. You can review it from [HERE](https://github.com/Sushisushi-sandesu/sushi/blob/contributeMD/CONTRIBUTING.md).

**Comment by ganmacs** [comment]
:+1:

**Comment by takuti** [comment]
[LGTM](http://lgtm.in/i/oEkAbqQ3q)

**Comment by tomoasleep** [comment]
LGTM

**Pull request merged**
